export const data = [

    {
      name: "Beşiktaş",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Logo_of_Be%C5%9Fikta%C5%9F_JK.svg/391px-Logo_of_Be%C5%9Fikta%C5%9F_JK.svg.png",
      statistics: ["BJK", "Siyah, Beyaz", "1903", "BJK Inönü Vodafone Park"],
      url: "https://www.bjk.com.tr",
      colorCode: ["#000000", "#FFFFFF"],
    },
    {
      name: "Adana Demirspor",
      img: "https://upload.wikimedia.org/wikipedia/tr/5/5f/Adanademirspor.png",
      statistics: ["ADS", "Mavi, Beyaz", "1940", "5 Ocak Fatih Terim Stadyumu"],
      url: "https://www.adanademirspor.org.tr",
      colorCode: ["#0000FF", "#FFFFFF"],
    },
    {
      name: "Alanyaspor",
      img: "https://upload.wikimedia.org/wikipedia/tr/2/29/Alanyaspor_logo.png",
      statistics: [
        "ALY",
        "Turuncu, Yeşil",
        "1948",
        "Bahçeşehir Okulları Stadyumu",
      ],
      url: "https://www.alanyaspor.org.tr",
      colorCode: ["#FFA500", "#008000"],
    },
    {
      name: "Ankaragücü",
      img: "https://upload.wikimedia.org/wikipedia/tr/9/97/MKE_Ankarag%C3%BCc%C3%BC_logo.png",
      statistics: ["ANK", "Sarı, Lacivert", "1911", "Eryaman Stadyumu"],
      url: "https://www.ankaragucu.org.tr",
      colorCode: ["#FFFF00", "#000080"],
    },

    {
      name: "Fenerbahçe",
      img: "https://upload.wikimedia.org/wikipedia/tr/8/86/Fenerbah%C3%A7e_SK.png",
      statistics: [
        "FB",
        "Sarı, Lacivert",
        "1907",
        "Ülker Stadyumu Fenerbahçe Şükrü Saracoğlu Spor Kompleksi",
      ],
      url: "https://www.fenerbahce.org",
      colorCode: ["#FFFF00", "#000080"],
    },
    {
      name: "Galatasaray",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Galatasaray_Sports_Club_Logo.png/481px-Galatasaray_Sports_Club_Logo.png",
      statistics: ["GS", "Sarı, Kırmızı", "1905", "Türk Telekom Stadyumu"],
      url: "https://www.galatasaray.org",
      colorCode: ["#FFFF00", "#FF0000"],
    },
    {
      name: "İstanbul Başakşehir",
      img: "https://upload.wikimedia.org/wikipedia/tr/c/cd/%C4%B0stanbul_Ba%C5%9Fak%C5%9Fehir_FK.png",
      statistics: ["IBFK", "Turuncu, Lacivert", "1990", "Fatih Terim Stadyumu"],
      url: "https://www.ibfk.com.tr",
      colorCode: ["#FFA500", "#000080"],
    },
    {
      name: "Fatih Karagümrük",
      img: "https://upload.wikimedia.org/wikipedia/tr/9/90/Fatihkaragumruk.png",
      statistics: [
        "KAR",
        "Kırmızı, Siyah",
        "1926",
        "Atatürk Olimpiyat Stadyumu",
      ],
      url: "https://www.fatihkaragumruk.org",
      colorCode: ["#FF0000", "#000000"],
    },
    {
      name: "Kayserispor",
      img: "https://upload.wikimedia.org/wikipedia/tr/thumb/c/c2/Kayserispor_logosu.png/600px-Kayserispor_logosu.png",
      statistics: ["KYS", "Sarı, Kırmızı", "1966", "Kadir Has Stadium"],
      url: "https://www.kayserispor.org.tr",
      colorCode: ["#FFFF00", "#FF0000"],
    },
    {
      name: "Kasımpaşa",
      img: "https://upload.wikimedia.org/wikipedia/tr/6/68/Kasimpasa_2012.png",
      statistics: ["KAS", "Lacivert, Beyaz", "1921", "doğan Stadyumu"],
      url: "https://www.kasimpasa.com.tr",
      colorCode: ["#000080", "#FFFFFF"],
    },
    {
      name: "Konyaspor",
      img: "https://upload.wikimedia.org/wikipedia/tr/4/41/Konyaspor_1922.png",
      statistics: [
        "KON",
        "Yeşil, Beyaz",
        "1922",
        "Medaş Konya Büyükşehir Stadyumu",
      ],
      url: "https://www.konyaspor.org.tr",
      colorCode: ["#008000", "#FFFFFF"],
    },
    {
      name: "Sivasspor",
      img: "https://upload.wikimedia.org/wikipedia/tr/8/80/Sivasspor.png",
      statistics: ["SVS", "Kırmızı, Beyaz", "1967", "Yeni 4 Eylül Stadyumu"],
      url: "https://www.sivasspor.org.tr",
      colorCode: ["#FF0000", "#FFFFFF"],
    },
    {
      name: "Trabzonspor",
      img: "https://upload.wikimedia.org/wikipedia/tr/a/ab/TrabzonsporAmblemi.png",
      statistics: ["TS", "Bordo, Mavi", "1967", "Medical Park Stadyumu"],
      url: "https://www.trabzonspor.org.tr",
      colorCode: ["#800000", "#0000FF"],
    },
    {
      name: "Ümraniyespor",
      img: "https://upload.wikimedia.org/wikipedia/tr/7/75/%C3%9Cmraniyespor_Logosu.png",
      statistics: ["ÜMR", "Kırmızı, Beyaz", "1938", "Ümraniye İlçe Stadyumu"],
      url: "https://www.umraniyespor.org.tr",
      colorCode: ["#FF0000", "#FFFFFF"],
    },
    {
      name: "İstanbulspor",
      img: "https://upload.wikimedia.org/wikipedia/tr/thumb/e/ed/IstanbulsporAS.png/515px-IstanbulsporAS.png",
      statistics: ["İST", "Sarı, Siyah", "1926", "Necmi Kadıoğlu Stadyumu"],
      url: "https://www.istanbulspor.org.tr",
      colorCode: ["#FFFF00", "#000000"],
    },
    {
      name: "Giresunspor",
      img: "https://upload.wikimedia.org/wikipedia/tr/c/c1/Giresunspor.png",
      statistics: ["GRS", "Yeşil, Beyaz", "1925", "Giresun Atatürk Stadyumu"],
      url: "https://www.giresunspor.org.tr",
      colorCode: ["#008000", "#FFFFFF"],
    },
  
];
